In [3]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [6]:
np.array([1, 2, 3]), type(np.array([1, 2, 3]))

(array([1, 2, 3]), numpy.ndarray)

In [7]:
np.array([1, 2, 3, "hello"])

array(['1', '2', '3', 'hello'], dtype='<U11')

In [ ]:
array = np.array([1, 2, 3], dtype=np.int8)
array, array.dtype

(array([1, 2, 3]), dtype('int32'))

In [9]:
2 ** 8

256

In [10]:
2 **8 - 1

255

In [11]:
bin (2**8-1)

'0b11111111'

In [15]:
array = np.array([1, 2, 3, 255], dtype=np.int8)
array
#255 reprezinta nr total de biti, si vine la jumatate pentru ca ia si jumatatea negativa

C:\Users\alina\AppData\Local\Temp\ipykernel_4484\1357701524.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 255 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array = np.array([1, 2, 3, 255], dtype=np.int8)


array([ 1,  2,  3, -1], dtype=int8)

In [17]:
array = np.array([1, 2, 3, 127, -127], dtype=np.int8)
array

array([   1,    2,    3,  127, -127], dtype=int8)

In [20]:
array = np.array([1, 2, 3, 128, 256], dtype=np.int8)
array

C:\Users\alina\AppData\Local\Temp\ipykernel_4484\2585334837.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array = np.array([1, 2, 3, 128, 256], dtype=np.int8)
C:\Users\alina\AppData\Local\Temp\ipykernel_4484\2585334837.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array = np.array([1, 2, 3, 128, 256], dtype=np.int8)


array([   1,    2,    3, -128,    0], dtype=int8)