In [1]:
import numpy as np


In [2]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
np.array(range(7))

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
np.arange(7, 15)

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#afiseaza numarele de la 7 la 15 din 3 in 3
np.arange(7, 15, 3)

array([ 7, 10, 13])