In [1]:
import numpy as np

In [4]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 300])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20, 300])

In [9]:
array.min(), array.max(), min(array), max(array)

(10, 500, 10, 500)

In [6]:
array.sum()

1274

In [7]:
array.mean()

141.55555555555554

In [8]:
array.sum(), sum(array)

(1274, 1274)

In [10]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 300])
array.min(), array.argmin()

(10, 3)

In [11]:
array.max(), array.argmax()

(500, 2)

In [12]:
l = [23, 41, 500, 10, 40, 30, 310, 20, 300]
l.index(30)

5

In [13]:
array[array>300]

array([500, 310])

In [14]:
array[-1]

300

In [15]:
array[-2:]

array([ 20, 300])

In [16]:
array[array % 2 ==0]

array([500,  10,  40,  30, 310,  20, 300])

In [17]:
array[(array % 2 ==0) & (array > 50)]

array([500, 310, 300])

In [18]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 300])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20, 300])

In [19]:
array[(array % 3 == 0) | (array < 40)]

array([ 23,  10,  30,  20, 300])